# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Multi Jobs Workflow

on:
  push:

jobs:
  Build_Deploy:

    runs-on: self-hosted

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Build with Maven
      run: mvn clean install
      
    - name: Zip the code
      uses: papeloto/action-zip@v1
      with:
          dest: App.zip
          
    - name: Check Directory
      run: dir
      
    - name: Send for Scan
      run: move App.zip C:\Users
      #\\hqcelfs01\xchange\Temp_AEPCommon\Vishali\
      

   
  
